### PR TITLE
fix: unable to bind ngIf in angular 17+

### LINKED ISSUE #8884: Bug: MockRender throws an error on mat-tab
In Angular Version 17 MockRender throws errors when a Component contains a Material Tab <mat-tab>

For each <mat-tab> contained in a Components Template an error is written to the console for each <mat-tab> element in the template. If you have 3 tabs you will get the same error repeated 3 times in the console.

The test still gets a PASS outcome despite the exceptions. The problem comes with DevOps Pipelines. If you include the execution of the tests as part of the pipeline the Release will fail due to these errors.

> jest -c jest.config.js

  console.error
    NG0303: Can't bind to 'ngIf' since it isn't a known property of 'div' (used in the '_MatTab' component template).
    If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is included in the '@Component.imports' of this component.

      at reportUnknownPropertyError (node_modules/@angular/core/fesm2022/core.mjs:9757:17)
      at handleUnknownPropertyError (node_modules/@angular/core/fesm2022/core.mjs:9750:5)
      at elementPropertyInternal (node_modules/@angular/core/fesm2022/core.mjs:11717:13)
      at ɵɵproperty (node_modules/@angular/core/fesm2022/core.mjs:21280:9)
      at MockOf_MatTab_Template (ng:/MockOf_MatTab.js:60:9)
      at executeTemplate (node_modules/@angular/core/fesm2022/core.mjs:11268:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12791:13)
      at detectChangesInView$1 (node_modules/@angular/core/fesm2022/core.mjs:13015:9)
      at detectChangesInViewIfAttached (node_modules/@angular/core/fesm2022/core.mjs:12978:5)
      at detectChangesInComponent (node_modules/@angular/core/fesm2022/core.mjs:12967:5)
      at detectChangesInChildComponents (node_modules/@angular/core/fesm2022/core.mjs:13028:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12841:13)
      at detectChangesInView$1 (node_modules/@angular/core/fesm2022/core.mjs:13015:9)
      at detectChangesInViewIfAttached (node_modules/@angular/core/fesm2022/core.mjs:12978:5)
      at detectChangesInComponent (node_modules/@angular/core/fesm2022/core.mjs:12967:5)
      at detectChangesInChildComponents (node_modules/@angular/core/fesm2022/core.mjs:13028:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12841:13)
      at detectChangesInView$1 (node_modules/@angular/core/fesm2022/core.mjs:13015:9)
      at detectChangesInViewIfAttached (node_modules/@angular/core/fesm2022/core.mjs:12978:5)
      at detectChangesInComponent (node_modules/@angular/core/fesm2022/core.mjs:12967:5)
      at detectChangesInChildComponents (node_modules/@angular/core/fesm2022/core.mjs:13028:9)
      at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12841:13)
      at detectChangesInView$1 (node_modules/@angular/core/fesm2022/core.mjs:13015:9)
      at detectChangesInViewWhileDirty (node_modules/@angular/core/fesm2022/core.mjs:12732:5)
      at detectChangesInternal (node_modules/@angular/core/fesm2022/core.mjs:12714:9)
      at ViewRef$1.detectChanges (node_modules/@angular/core/fesm2022/core.mjs:13310:9)
      at node_modules/@angular/core/fesm2022/testing.mjs:352:36
      at _ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:412:32)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing.umd.js:2164:43)
      at _ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:38)
      at Object.onInvoke (node_modules/@angular/core/fesm2022/core.mjs:18555:33)
      at _ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:38)
      at ZoneImpl.run (node_modules/zone.js/bundles/zone.umd.js:147:47)
      at NgZone.run (node_modules/@angular/core/fesm2022/core.mjs:18406:28)
      at PseudoApplicationComponentFixture.detectChanges (node_modules/@angular/core/fesm2022/testing.mjs:351:22)
      at template (node_modules/ng-mocks/webpack:/ng-mocks/libs/ng-mocks/src/lib/mock-render/mock-render-factory.ts:162:37)
      at t.MockRender (node_modules/ng-mocks/index.js:1:219334)
      at src/app/app.component.spec.ts:10:35
      at _ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:412:32)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing.umd.js:2164:43)
      at _ZoneDelegate.invoke (node_modules/zone.js/bundles/zone.umd.js:411:38)
      at ZoneImpl.run (node_modules/zone.js/bundles/zone.umd.js:147:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing.umd.js:450:38)

 PASS  src/app/app.component.spec.ts
  AppComponent
    √ should create the app (310 ms)

I have attached a zip file containing a simple Angular Application that demonstrates the issue. I have removed the node modules to reduce the size of the file.

### Expected vs actual behavior
The tests of the Component containing Material Tabs should pass without throwing errors.

[mat-tab-error-issue.zip](https://github.com/help-me-mom/ng-mocks/files/15182784/mat-tab-error-issue.zip)

### PR DESCRIPTION
**Pull request by sabrina-10kc**
When component templates contain child templates, they are replaced with a mock template that contains a `*ngIf` this causes a failure when the component doesn't have NgIf imported.

Though this problem likely exists in some pre-angular 17 situations, it has been causing new failures to appear as people upgrade since 3rd party angular components are starting to use the new control flow syntax and no longer import `CommonModule` / `NgIf`.

Instead the mock template now uses `@if` syntax if angular is 17 or higher.

Fixes #8884

### CODE REVIEW

**Comment by sabrina-10kc** [comment]
@satanTime Is there anything I need to change in this PR to help it get in & released ? (other than rebasing of course)

This issue is currently preventing use of `errorOnUnknownElements` for me

**Comment by satanTime** [comment]
Hi @sabrina-10kc,

Thank you for your contribution. 
Next week I'll be working on the rep and take a look at the PR.

**Comment by donroyco** [comment]
Any update on this PR, @satanTime ? It would be really helpful to have this fixed.

**Comment by mikeysteele** [comment]
It would be great to get this merged. This can cause otherwise good tests to fail depending on when the error is thrown.

**Comment by JsantosDK** [comment]
Hello @satanTime when can you approve this?
It's almost 2 months now since your last comment on it.

**Comment by satanTime** [comment]
I wish it was so easy. 
The thing there is that a line of code which was covered by tests now is simply ignored. 
Because of that I need to investigate whether this is the only way to fix the issue, because the line is covered well currently in a17 and a18.

**Comment by JsantosDK** [comment]
@satanTime after reading this comment, please re-consider moving the version to the approach of angular and the current approach that the library has.

It is a problem for people who want to use it to have to wait for months for something to be fix, because you need to be sure it works on all versions.
It is a problem for people who want to contribute, since they need to ensure that it works on all versions, make the fix so easy that you can understand and then wait for god knows how long until before it is merged.

The angular team just gave a speech a few days ago saying that they realize by time.
Everybody that uses things in the angular ecosystem is used to this way of release management.

Me and others want to contribute, but the current approach means everything will always fall on you.
You are blocking other from helping because you need to be 100% sure of everything, at the same time you don't have time.

Yesterday, I installed the lib on a new machine to contribute with the specs and it took over 1h. The approach to develop the lib already takes 6GB in docker to be run, this is not a normal amount of space for a library that like you say, is just a wrapper for making life easier. Will this keep going until the machine reaches it's limit? 

People want to help, but it seems you don't want to be help, you don't really want others to collaborate with you.

What would it take to help?
Not just on this issue, but on the lib itself? 
Or do you really want to keep going like, until eventually the lib faces so many issues that it dies out due to your lack of time?

I'm working on the schematics, but if there is anything I can help, tell.
And please, consider the change in versioning since the consumers of the lib don't agree with you and it doesn't match the way the angular ecosystem moves.

**Comment by satanTime** [comment]
Not sure I understand your point. Old syntax is support in all angular versions it wasn't removed from a17 or a18. So I'm not sure how release change can improve that. It still both syntax should be supported for a18 and a17.

**Comment by JsantosDK** [comment]
My main issue is that this PR has been opened for a long time without any feedback from anybody.

Really seems like you don't have the time to support the lib alone, but don't allow much help.

**Comment by satanTime** [comment]
Feel free to help, a test which  would cover both beaches instead of ignoring one would help.

**Comment by JsantosDK** [comment]
Ok, will try to get it done between today and tomorrow.

**Comment by satanTime** [comment]
Great. Thanks. Is that branch cannot be covered at all - that’s also fine. I just need to be sure that that’s exactly like that.

**Comment by JsantosDK** [comment]
@satanTime I reviewed this with the focus on reaching the other part of the branch.
Only way to do so, was modify the specs so that it has 2 branches, one for angular 16 and below, and another for angular 17 and above.

When I did this, I got the following results:

Angular 17+ branch:
- Original specs pass;
- Added spec passes (expected, due to the if statement exiting before the test is reached);

Angular 16 and below:
- Original specs pass(expected, due to the if statement exiting before the test is reached);
- Added spec fails with the same error as originally: `NG0303: Can't bind to 'ngIf' since it isn't a known property of 'ng-template' (used in the 'TargetComponent' component template)`;

From what I can tell, I'm worried that if this PR is merged, and a new version is released, in an Angular 16 or below app, it will break it. I may try to make a build and tested this myself with an actual use case, but would like your input on this before proceeding.

In example you can find the spec file I used:
```ts
import {
  Component,
  ContentChild,
  NgModule,
  TemplateRef,
  VERSION,
} from '@angular/core';

import { MockBuilder, MockRender, ngMocks } from 'ng-mocks';

// @see https://github.com/help-me-mom/ng-mocks/issues/8884
describe('issue-8884', () => {
  ngMocks.throwOnConsole();

  describe('with a16 and below (added by me)', () => {
    if (Number.parseInt(VERSION.major, 10) > 16) {
      it('needs a16 or below', () => {
        expect(true).toBeTruthy();
      });

      return;
    }

    @Component({
      selector: 'app-target',
      template: `<ng-template [ngTemplateOutlet]="content" />`,
    })
    class TargetComponent {
      @ContentChild('content', {} as never)
      content?: TemplateRef<any>;
    }

    @NgModule({
      declarations: [TargetComponent],
    })
    class TargetModule {}

    beforeEach(() => MockBuilder(null, TargetModule));

    it('should create', () => {
      MockRender(`<app-target>Test content</app-target>`);

      expect(ngMocks.findInstance(TargetComponent)).toBeTruthy();
    });
  });

  describe('with a17+', () => {
    if (Number.parseInt(VERSION.major, 10) < 17) {
      it('needs a17+', () => {
        expect(true).toBeTruthy();
      });

      return;
    }

    describe('when standalone component does not import NgIf', () => {
      @Component({
        selector: 'app-standalone',
        standalone: true,
        template: `<ng-template [ngTemplateOutlet]="content" />`,
      })
      class StandaloneComponent {
        @ContentChild('content', {} as never)
        content?: TemplateRef<any>;
      }

      beforeEach(() => MockBuilder(null, StandaloneComponent));

      it('should create', () => {
        MockRender(`<app-standalone>Test content</app-standalone>`);

        expect(ngMocks.findInstance(StandaloneComponent)).toBeTruthy();
      });
    });

    describe('when NgIf is not available to a component in a module', () => {
      @Component({
        selector: 'app-target',
        template: `<ng-template [ngTemplateOutlet]="content" />`,
      })
      class TargetComponent {
        @ContentChild('content', {} as never)
        content?: TemplateRef<any>;
      }

      @NgModule({
        declarations: [TargetComponent],
      })
      class TargetModule {}

      beforeEach(() => MockBuilder(null, TargetModule));

      it('should create', () => {
        MockRender(`<app-target>Test content</app-target>`);

        expect(ngMocks.findInstance(TargetComponent)).toBeTruthy();
      });
    });
  });
});
```

**Review by satanTime — APPROVED** [review]

**Comment by satanTime** [comment]
[v14.13.1](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.13.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Pull request merged**
