### PR TITLE
Angular 17

### PR DESCRIPTION
**Pull request by PieterjanDeClippel**

### CODE REVIEW

**Comment by satanTime** [comment]
Hi @PieterjanDeClippel,

thank you for the PR, however, you need to add e2e tests for A17 to verify that current state of `ng-mocks` does work with it. An example is A16 or A15 in the e2e folder.

**Comment by chutch1122** [comment]
@satanTime I attempted to add e2e tests for an Angular 17 in my fork here: https://github.com/chutch1122/ng-mocks/commits/master

I am seeing some strange behavior with Angular 17 and Standalone components (Jasmine and Jest). Specifically, the `issue-2687` test suite is failing - but only when *all* of the tests in the file are executed. If I focus the failing test, that test passes. I suspect something isn't getting cleaned up/reset properly in the test environment.
 
## Jest
 Running all tests. One test fails.
Screenshot 2023-11-09 at 9 56 55 PM

Focusing the failing test from the previous test. It passes.
Screenshot 2023-11-09 at 9 58 16 PM

## Jasmine
Running all tests. One test fails.
Screenshot 2023-11-09 at 10 01 34 PM

Focusing the failing test from the previous test. It passes.
Screenshot 2023-11-09 at 10 01 55 PM

**Comment by PieterjanDeClippel** [comment]
@chutch1122 I think it's best to use your version and branch. I think you're almost there probably. Can you create a pull-request for your branch?

**Comment by satanTime** [comment]
Hi all.

There is an issue in Angular 17 which should be fixed first: https://github.com/angular/angular/issues/52817
Feel free to upvote it.

**Comment by PieterjanDeClippel** [comment]
@satanTime @chutch1122 A new angular version (probably with the patch) was just released 20 minutes ago

**Comment by satanTime** [comment]
[v14.12.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Pull request closed without merging**
